replicaCount: 1

image:
  repository: cp-kafka-custom
  tag: 7.6.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
env:
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@cp-kafka-release-kafka-chart:9093
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-kafka-release-kafka-chart:9092
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  CLUSTER_ID: 3zms-h-xqdsl7yyrhvreeg
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_LOG_RETENTION_MS: "600000"
  KAFKA_LOG_RETENTION_BYTES: "1000000000"
  KAFKA_LOG_SEGMENT_BYTES: "100000000"

configurationOverrides:
  listeners: PLAINTEXT://0.0.0.0:9092
  advertised.listeners: PLAINTEXT://cp-kafka-release-kafka-chart:9092
