apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "informer-chart.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "informer-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
