services:
  dwh_stock_bigdata:
    container_name: dwh-stock-bigdata
    build:
      context: .
      dockerfile: docker/Dockerfile.project
    image: dwh-stock-bigdata
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge