services:
  trainer:
    build:
      context: .
      dockerfile: docker-file/Dockerfile.informer
    container_name: informerAI-trainer
    image: informer-ai:2.0
    restart: no
    env_file:
      - ./.env
    command: python3 core/streaming/informerAI/train/ai_ticker_trainer.py
    networks:
      - kafka_network 
networks:
  kafka_network:
    driver: bridge
