services:
  predictor:
    container_name: informerAI_predictor
    image: informer_ai
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/Dockerfile.informer
    command: python3 core/streaming/informerAI/predict/ai_ticker_predictor.py
    restart: no
    networks:
      - kafka_network 
networks:
  kafka_network:
    driver: bridge