services:
  dwh_stock_bigdata:
    container_name: dwh-stock-bigdata
    build:
      context: .
      dockerfile: docker-file/Dockerfile.project
    image: dwh-stock-bigdata:2.0
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge