services:
  trainer:
    container_name: informerAI-trainer
    image: informer-ai
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/Dockerfile.informer
    command: python3 core/streaming/informerAI/train/ai_ticker_trainer.py
    restart: no
    networks:
      - kafka_network 
networks:
  kafka_network:
    driver: bridge
