services:
  trainer:
    container_name: informerAI_trainer
    image: informerAI
    build:
      context: .
      dockerfile: docker/Dockerfile.informer
    command: python3 core/streaming/informerAI/train/ai_ticker_trainer.py
    restart: no
    networks:
      - networkName: kafka_network
networks:
  kafka_network:
    driver: bridge