services:
  bitnami-kafka:
    build:
      context: . 
      dockerfile: docker-file/Dockerfile.bitnami-kafka
    container_name: bitnami-kafka
    image: bitnami-kafka:4.0.0-debian-12-r8
    restart: always
    ports:
      - "9092:9092"   # broker
      - "9093:9093"   # controller
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}                        # "broker,controller"
      KAFKA_CFG_LISTENERS: ${KAFKA_LISTENERS}                                # "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}          # "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}  # "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}  # "1@localhost:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES} # "CONTROLLER"
      KAFKA_CFG_LOG_DIRS: ${KAFKA_LOG_DIRS}                                   # "/bitnami/kafka/data"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      ALLOW_PLAINTEXT_LISTENER: "yes"

    networks:
      - kafka_network

  kafka-ui:
    build:
      context: . 
      dockerfile: docker-file/Dockerfile.kafka-ui 
    container_name: kafka-ui
    image: kafka-ui:v0.7.2
    restart: always
    depends_on:
      - bitnami-kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_UI_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: ${KAFKA_UI_BOOTSTRAP_SERVERS}
      KAFKA_CLUSTERS_0_KAFKA_VERSION: ${KAFKA_UI_KAFKA_VERSION}
    networks:
      - kafka_network
  influxdb:
    build:
      context: . 
      dockerfile: docker-file/Dockerfile.influxdb 
    container_name: influxdb
    image: influxdb:2.7.0
    # Environment variables for InfluxDB 2.x initial setup
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE:-setup} # Default to 'setup' if not set
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET} 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN} # This will be the token your app uses
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped
    networks:
      - kafka_network

  grafana:
    build:
      context: . 
      dockerfile: docker-file/Dockerfile.grafana 
    container_name: grafana
    image: grafana:10.4.2
    environment: # Use variables from .env for Grafana admin
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - kafka_network

  superset:
    build:
      context: . 
      dockerfile: docker-file/Dockerfile.superset 
    container_name: superset
    image: superset:5.0.0
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_USERNAME: ${SUPERSET_USERNAME}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      SUPERSET_RUN_HOST: ${SUPERSET_RUN_HOST}
      SUPERSET_RUN_PORT: ${SUPERSET_RUN_PORT}
      SUPERSET_CONFIG_PATH: /app/superset_config.py
    volumes:
      - superset_home:/app/superset_home
      - ./core/streaming/superset/config.py:/app/superset_config.py
    command: ["/bin/sh", "-c",
      "superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_USERNAME} --firstname ${SUPERSET_ADMIN_FIRSTNAME} --lastname ${SUPERSET_ADMIN_LASTNAME} --email ${SUPERSET_ADMIN_EMAIL} --password ${SUPERSET_PASSWORD} &&
      superset init &&
      superset run -h ${SUPERSET_RUN_HOST} -p ${SUPERSET_RUN_PORT}"
    ]
    restart: unless-stopped
    networks:
      - kafka_network

volumes:
  influxdb_data:
  grafana_data:
  superset_home:

networks:
  kafka_network:
    driver: bridge
