services:
  predictor:
    build:
      context: .
      dockerfile: docker-file/Dockerfile.informer
    container_name: informerAI-predictor
    image: informer-ai:2.0
    restart: no
    env_file:
      - ./.env
    command: python3 core/streaming/informerAI/predict/ai_ticker_predictor.py
    networks:
      - kafka_network 
networks:
  kafka_network:
    driver: bridge