apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  grafana_admin_user: {{ .Values.secrets.grafana_admin_user | b64enc }}
  grafana_admin_password: {{ .Values.secrets.grafana_admin_password | b64enc }}
  grafana_key: {{ .Values.secrets.grafana_key | b64enc }}
