apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-chart.fullname" . }}
  labels:
    {{- include "grafana-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
# service slector app map with deployment label app
  selector:
    app: {{ include "grafana-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
