replicaCount: 1

image:
  repository: informer-ai
  tag: "2.0"
  pullPolicy: Never
env:
  core:
    STREAM_TYPES: trade,ticker,bookTicker
  aws:
    AWS_DEFAULT_REGION: ap-southeast-1  
    BUCKET_NAME: binance-old-silver
    ROOT_DB: trade,ticker,bookTicker
    ATHENA_DB: binance
    S3_STAGING_DIR: s3://staging-binance-old-silver/    
  grafana:
    GRAFANA_URL: http://grafana-release-grafana-chart:3000   
    GRAFANA_DB_URL: http://influxdb-release-influxdb-chart:8086
  influxdb:
    INFLUXDB_URL: http://influxdb-release-influxdb-chart:8086 
    INFLUXDB_ORG: THANH_TINH
    INFLUXDB_BUCKET: realtime_crypto
  superset:
    SUPERSET_URL: http://superset-release-superset-chart:8088
  informer:
    # ==============================================================================
    # Informer AI Configuration
    # ==============================================================================
    AI_APP_NAME: Informer_AI
    # repartition number for Spark DataFrame
    REPARTITION: "12"
    # Ration of train:val:test for Trainer
    TRAIN_RATIO: "0.7"
    VAL_RATIO: "0.2"
    # Number data (row) run each batch ; 64 or 128
    BATCH_SIZE: "64"
    # Max 7 day (s3 set 7 day data stored) but it just upper Limit range
    N_DAYS_AGO: "2"
    # Make sure create enough batch 2000-200000(1 dir ~ 1 min data) 
    # Runable (tested) number is 180-300-100. (train time = 0:00 -> 0:50 )
    MAX_DIRECTORIES: "180"
    # SEQUENCE_LENGTH:PREDICTION_LENGTH = 3:1
    SEQUENCE_LENGTH: "300"
    # 1/3 of SEQUENCE_LENGTH
    PREDICTION_LENGTH: "100"
    # Number epoch, 200 will recomment, 20 was use to test
    NUM_EPOCHS: "20"
