apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.envFromSecret . }}
  labels:
    app.kubernetes.io/name: {{ include "superset.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.secret_key | b64enc }}
  ADMIN_USERNAME: {{ .Values.secret.admin_username | b64enc }}
  ADMIN_PASSWORD: {{ .Values.secret.admin_password | b64enc }}
  ADMIN_EMAIL: {{ .Values.secret.admin_email | b64enc }}
  SQLALCHEMY_DATABASE_URI: {{ .Values.secret.sqlalchemy_database_uri | b64enc }}
