version: '3.7'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8080:8080"  # Truy cập Kafka UI qua cổng 8080
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"  # Sửa lại từ localhost -> kafka
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"  # Sửa lại từ localhost -> zookeeper
      KAFKA_CLUSTERS_0_KAFKA_VERSION: "2.7.0"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    restart: always
    ports:
      - "8081:8081"  # Truy cập Schema Registry qua cổng 8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"  # Sửa lại từ localhost -> zookeeper
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"  # Lắng nghe trên cổng 8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"  # Thêm dòng này để Schema Registry biết Kafka ở đâu
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "_schemas"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
