version: "3.8"
services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: athena_superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      ATHENA_DB: ${ATHENA_DB}
      S3_STAGING_DIR: ${S3_STAGING_DIR}
      SUPERSET_DATABASE_URI: "awsathena+rest://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@athena.${AWS_DEFAULT_REGION}.amazonaws.com/${ATHENA_DB}?s3_staging_dir=${S3_STAGING_DIR}"
      SUPERSET_CONFIG_PATH: /app/pythonpath/config.py
      
    volumes:
      - superset_home:/app/superset_home
      - ../core/streaming/superset/config.py:/app/pythonpath/config.py

    command: ["/bin/sh", "-c",
      "superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_USERNAME} --firstname Superset --lastname Admin --email admin@superset.local --password ${SUPERSET_PASSWORD} &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088"
    ]

    restart: unless-stopped

volumes:
  superset_home:
