apiVersion: v1
kind: Secret
metadata:
  name: project-secret
type: Opaque
data:
  # core
  SPARK_LOCAL_DIR: {{ .Values.secret.core.SPARK_LOCAL_DIR | b64enc }}
  SPARK_MODE: {{ .Values.secret.core.SPARK_MODE | b64enc }}
  WSS_ENDPOINT: {{ .Values.secret.core.WSS_ENDPOINT | b64enc }}
  URL_TOP: {{ .Values.secret.core.URL_TOP | b64enc }}
  LIMIT: {{ .Values.secret.core.LIMIT | b64enc }}
  STREAM_TYPES: {{ .Values.secret.core.STREAM_TYPES | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.secret.core.AWS_DEFAULT_REGION | b64enc }}
  BUCKET_NAME: {{ .Values.secret.core.BUCKET_NAME | b64enc }}
  ROOT_DB: {{ .Values.secret.core.ROOT_DB | b64enc }}
  ATHENA_DB: {{ .Values.secret.core.ATHENA_DB | b64enc }}
  S3_STAGING_DIR: {{ .Values.secret.core.S3_STAGING_DIR | b64enc }}
  BOOTSTRAP_SERVERS: {{ .Values.secret.core.BOOTSTRAP_SERVERS | b64enc }}
  BINANCE_TOPIC: {{ .Values.secret.core.BINANCE_TOPIC | b64enc }}
  NUM_PARTITIONS: {{ .Values.secret.core.NUM_PARTITIONS | b64enc }}
  GRAFANA_URL: {{ .Values.secret.core.GRAFANA_URL | b64enc }}
  GRAFANA_DB_URL: {{ .Values.secret.core.GRAFANA_DB_URL | b64enc }}
  INFLUXDB_URL: {{ .Values.secret.core.INFLUXDB_URL | b64enc }}
  INFLUXDB_ORG: {{ .Values.secret.core.INFLUXDB_ORG | b64enc }}
  INFLUXDB_BUCKET: {{ .Values.secret.core.INFLUXDB_BUCKET | b64enc }}
  SUPERSET_URL: {{ .Values.secret.core.SUPERSET_URL | b64enc }}

  # aws
  AWS_ACCESS_KEY_ID: {{ .Values.secret.aws.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.aws.AWS_SECRET_ACCESS_KEY | b64enc }}

  # grafana
  GRAFANA_KEY: {{ .Values.secret.grafana.GRAFANA_KEY | b64enc }}
  GRAFANA_ADMIN_USER: {{ .Values.secret.grafana.GRAFANA_ADMIN_USER | b64enc }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secret.grafana.GRAFANA_ADMIN_PASSWORD | b64enc }}

  # influxdb
  INFLUXDB_TOKEN: {{ .Values.secret.influxdb.INFLUXDB_TOKEN | b64enc }}

  # superset
  SUPERSET_USERNAME: {{ .Values.secret.superset.SUPERSET_USERNAME | b64enc }}
  SUPERSET_PASSWORD: {{ .Values.secret.superset.SUPERSET_PASSWORD | b64enc }}
  SUPERSET_SECRET_KEY: {{ .Values.secret.superset.SUPERSET_SECRET_KEY | b64enc }}
