services:
  superset:
    image: apache/superset:5.0.0
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_USERNAME: ${SUPERSET_USERNAME}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      SUPERSET_RUN_HOST: ${SUPERSET_RUN_HOST}
      SUPERSET_RUN_PORT: ${SUPERSET_RUN_PORT}
      SUPERSET_CONFIG_PATH: ${SUPERSET_CONFIG_PATH}
      WTF_CSRF_ENABLED: ${WTF_CSRF_ENABLED}
      ENABLE_CORS: ${ENABLE_CORS}

    volumes:
      - superset_home:/app/superset_home
      - ./core/streaming/superset/config.py:/app/superset_config.py
    command: ["/bin/sh", "-c",
      "superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_USERNAME} --firstname ${SUPERSET_ADMIN_FIRSTNAME} --lastname ${SUPERSET_ADMIN_LASTNAME} --email ${SUPERSET_ADMIN_EMAIL} --password ${SUPERSET_PASSWORD} &&
      superset init &&
      superset run -h ${SUPERSET_RUN_HOST} -p ${SUPERSET_RUN_PORT}"]
    networks:
      - kafka_network

volumes:
  superset_home:

networks:
  kafka_network:
    external: true
