apiVersion: apps/v1
kind: Deployment
metadata:
metadata:
  name: {{ include "kafka-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kafka-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
{{- range .Values.service.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
{{- end }}

          env:
  {{- with .Values.env }}
  {{- range $key, $value := . }}
            - name: {{ $key }}
              value: "{{ $value }}"
  {{- end }}
  {{- end }}