apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwh-stock-bigdata-release
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dwh-stock-bigdata-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dwh-stock-bigdata-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ports:
          #   - containerPort: 8080

          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret

          env:
            # core
            - name: WSS_ENDPOINT
              value: {{ .Values.env.core.WSS_ENDPOINT }}
            - name: URL_TOP
              value: {{ .Values.env.core.URL_TOP }}
            - name: LIMIT
              value: "{{ .Values.env.core.LIMIT }}"
            - name: STREAM_TYPES
              value: {{ .Values.env.core.STREAM_TYPES }}

            # aws
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.env.aws.AWS_DEFAULT_REGION }}
            - name: BUCKET_NAME
              value: {{ .Values.env.aws.BUCKET_NAME }}
            - name: ROOT_DB
              value: {{ .Values.env.aws.ROOT_DB }}
            - name: ATHENA_DB
              value: {{ .Values.env.aws.ATHENA_DB }}
            - name: S3_STAGING_DIR
              value: {{ .Values.env.aws.S3_STAGING_DIR }}

            # kafka
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.env.kafka.BOOTSTRAP_SERVERS }}
            - name: BINANCE_TOPIC
              value: {{ .Values.env.kafka.BINANCE_TOPIC }}
            - name: NUM_PARTITIONS
              value: "{{ .Values.env.kafka.NUM_PARTITIONS }}"

            # grafana
            - name: GRAFANA_URL
              value: {{ .Values.env.grafana.GRAFANA_URL }}
            - name: GRAFANA_DB_URL
              value: {{ .Values.env.grafana.GRAFANA_DB_URL }}

            # influxdb
            - name: INFLUXDB_URL
              value: {{ .Values.env.influxdb.INFLUXDB_URL }}
            - name: INFLUXDB_ORG
              value: {{ .Values.env.influxdb.INFLUXDB_ORG }}
            - name: INFLUXDB_BUCKET
              value: {{ .Values.env.influxdb.INFLUXDB_BUCKET }}

            # superset
            - name: SUPERSET_URL
              value: {{ .Values.env.superset.SUPERSET_URL }}
