apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.aws.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.aws.AWS_SECRET_ACCESS_KEY | b64enc }}

  GRAFANA_KEY: {{ .Values.secret.grafana.GRAFANA_KEY | b64enc }}
  GRAFANA_ADMIN_USER: {{ .Values.secret.grafana.GRAFANA_ADMIN_USER | b64enc }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secret.grafana.GRAFANA_ADMIN_PASSWORD | b64enc }}

  INFLUXDB_TOKEN: {{ .Values.secret.influxdb.INFLUXDB_TOKEN | b64enc }}

  SUPERSET_USER: {{ .Values.secret.superset.SUPERSET_USER | b64enc }}
  SUPERSET_PASSWORD: {{ .Values.secret.superset.SUPERSET_PASSWORD | b64enc }}
  SUPERSET_SECRET_KEY: {{ .Values.secret.superset.SUPERSET_SECRET_KEY | b64enc }}
