apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "superset-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "superset-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}


spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "superset-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "superset-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      initContainers:
        - name: superset-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "==> SQLALCHEMY_DATABASE_URI: $SQLALCHEMY_DATABASE_URI" && \
              superset db upgrade && \
              (superset fab create-admin \
                --username "$ADMIN_USERNAME" \
                --firstname Superset \
                --lastname Admin \
                --email "$ADMIN_EMAIL" \
                --password "$ADMIN_PASSWORD" || true) && \
              superset init
          envFrom:
            - secretRef:
                name: superset-secret
          env:
            - name: PYTHONPATH
              value: /app/pythonpath
            - name: SUPERSET_CONFIG_PATH
              value: /app/pythonpath/superset_config.py
            - name: WTF_CSRF_ENABLED
              value: "{{ .Values.config.wtf_csrf_enabled }}"
            - name: ENABLE_CORS
              value: "{{ .Values.config.enable_cors }}" 
            - name: ENABLE_PROXY_FIX
              value: "{{ .Values.config.enable_proxy_fix }}"
            - name: SUPERSET_WEBSERVER_ADDRESS
              value: "{{ .Values.config.superset_webserver_address }}"
            - name: SUPERSET_WEBSERVER_PORT
              value: "{{ .Values.config.superset_webserver_port }}"

          volumeMounts:
            - name: superset-config
              mountPath: /app/pythonpath/superset_config.py
              subPath: superset_config.py

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: superset-secret
          env:
            - name: PYTHONPATH
              value: /app/pythonpath
            - name: SUPERSET_CONFIG_PATH
              value: /app/pythonpath/superset_config.py
            - name: WTF_CSRF_ENABLED
              value: "{{ .Values.config.wtf_csrf_enabled }}"
            - name: ENABLE_CORS
              value: "{{ .Values.config.enable_cors }}" 
            - name: ENABLE_PROXY_FIX
              value: "{{ .Values.config.enable_proxy_fix }}"
            - name: SUPERSET_WEBSERVER_ADDRESS
              value: "{{ .Values.config.superset_webserver_address }}"
            - name: SUPERSET_WEBSERVER_PORT
              value: "{{ .Values.config.superset_webserver_port }}"

          volumeMounts:
            - name: superset-config
              mountPath: /app/pythonpath/superset_config.py
              subPath: superset_config.py
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5

      volumes:
        - name: superset-config
          configMap:
            name: {{ include "superset-chart.fullname" . }}-config
            items:
              - key: superset_config.py
                path: superset_config.py
