replicaCount: 1

image:
  repository: superset-custom
  tag: 5.0.0
  #pullPolicy: IfNotPresent
  pullPolicy: Never



service:
  type: ClusterIP
  port: 8088

config:
  wtf_csrf_enabled: True
  enable_cors: True
#             self.ATHENA_URI = f"awsathena+rest://{self.AWS_ACCESS_KEY_ID}:{self.AWS_SECRET_ACCESS_KEY}@athena.{self.AWS_REGION}.amazonaws.com/{self.ATHENA_DB}?s3_staging_dir={self.S3_STAGING_DIR}"

